 git:
  depth: 10
 language: scala
 scala:
   - 2.10.4
   - 2.11.4
 matrix:
   allow_failures:
     - scala: 2.11.4
 jdk:
   - openjdk6
   - openjdk7
   - oraclejdk7
   - oraclejdk8
 sudo: false
   
 script: "sbt ++$TRAVIS_SCALA_VERSION scalastyle test"
