 language: scala
 scala:
   - 2.10.4
   - 2.11.1
 matrix:
   allow_failures:
     - scala: 2.11.1
 jdk:
   - openjdk6
   - openjdk7
   - oraclejdk7
   - oraclejdk8
   
 script: "sbt ++$TRAVIS_SCALA_VERSION scalastyle test"
