 language: scala
 scala:
   - 2.10.4
   - 2.11.0-RC3
 matrix:
   allow_failures:
     - scala: 2.11.0-RC3
 jdk:
   - oraclejdk7
   - openjdk6
   - openjdk7
   
 script: "sbt ++$TRAVIS_SCALA_VERSION scalastyle test"
